### ISSUE TITLE
Can't find the paper

### ISSUE THREAD

**Issue by xizaoqu** [OpenMotionLab/MotionGPT#1]
The arxiv link points to "Executing your Commands via Motion Diffusion in Latent Space".

**Comment by ChenFengYe** [comment]
Thanks for your attention. We are working on it. You can read the paper below.

[MotionGPT.pdf](https://github.com/OpenMotionLab/MotionGPT/files/11798475/MotionGPT.pdf)

**Comment by ChenFengYe** [comment]
Please visit our arxiv page. If you have any other questions, please feel free to ask.

https://arxiv.org/pdf/2306.14795

**Comment by jacob-kang** [comment]
@ChenFengYe Hi. Thanks for your great works. I wonder which conference or journal will you submit this awesome paper? Thanks.

**Comment by ChenFengYe** [comment]
Sorry jacob! According to the conference rules, we can hardly tell anything about this submission. It is not permitted to introduce this conference in our work. If you are interested in computer vision conferences, just google it. Thanks!

> @ChenFengYe Hi. Thanks for your great works. I wonder which conference or journal will you submit this awesome paper? Thanks.

**Comment by xizaoqu** [comment]
> 

Great, thanks.
