### ISSUE TITLE
I am deadly

### ISSUE THREAD

**Issue by hyeonmin11** [OpenMotionLab/MotionGPT#11]
looking forward to your release!!!!!!!!!!!!!! Can't wait your amazing work

**Comment by ChenFengYe** [comment]
Please be alive until release. >_<
We are working hard on it!

**Comment by hyeonmin11** [comment]
Hi, I thought code would be released until this month because I saw your comment in other issue that code will be released in two months in June.
Can you notice us specifically or approximately about the plan of your code release?
Thanks

**Comment by ChenFengYe** [comment]
@hyeonmin11 Hi, thank you for your kind attention.
We plan to release the first version (v1.0) of MotionGPT on September 9th.
Furthermore, more models and add-ons will also be introduced in the future.
We hope this work could help your research or development. Thanks!

**Comment by hyeonmin11** [comment]
Thanks!
