### ISSUE TITLE
Missing t2m/VQVAEV3_CB1024_CMT_H1024_NRES3

### ISSUE THREAD

**Issue by csvt32745** [OpenMotionLab/MotionGPT#14]
Hi, thanks for releasing the easily understandable code :smile_cat: 
While I run the webui-app successfully, there are some artifacts due to missing files that I replaced probably.

--
Update:
Chaging `VQVAEV3_CB1024_CMT_H1024_NRES3` to `Decomp_SP001_SM001_H512` works well for generating motion!
![2023-09-10-14_17_1244086](https://github.com/OpenMotionLab/MotionGPT/assets/17510515/210a1969-d999-4121-96c5-c364f59863de)

--
Example (using mean/std from HumanML3D repo):
`Can you show me that a person does three straight jumping jacks ?`
![2023-09-10-13_59_2068067](https://user-images.githubusercontent.com/17510515/266817377-7a5e095a-a552-4e6e-8337-bbeaa980bdf9.gif)

- `dis_data_root = pjoin(cfg.DATASET.HUMANML3D.MEAN_STD_PATH, 't2m', "VQVAEV3_CB1024_CMT_H1024_NRES3", "meta")`
    - The provided data didn't include `VQVAEV3_CB1024_CMT_H1024_NRES3` in `deps/t2m/t2m`
    - Replaced by `Mean.npy` and `Std.npy` in HumanML3D repo
- `configs/webui.yaml`
    - `Test.CHECKPOINTS`: `...ckpt` to `...tar`
- `configs/lm/default.yaml`
    - `params.model_path`: `../memData/deps/flan-t5-base` to `google/flan-t5-base`
- `configs/assets.yaml`
    - `model.whisper_path`: `deps/whisper-large-v2` to `openai/whisper-large-v2`
- HumanML dataset in `datasets/humanml3d`
    - Use a single `012314.npy` from HumanML3D repo as dataset

Thanks again :smile:

**Comment by ChenFengYe** [comment]
Thanks, bro. We are working on it! 
Wait for a second. (>_<)

**Comment by ChenFengYe** [comment]
We have fixed this issue. You can check the new release. Thanks!

**Comment by kruzel** [comment]
hi,
thanks for the great code.

I'm trying to run the demo via app.py but get related error, although the files exist.: 
"FileNotFoundError: [Errno 2] No such file or directory: 'deps/t2m/t2m/VQVAEV3_CB1024_CMT_H1024_NRES3/meta/mean.npy'"

error log:
![image](https://github.com/OpenMotionLab/MotionGPT/assets/975963/60f97ec0-869a-4cff-9178-9dbbdbb91699)

files:
![image](https://github.com/OpenMotionLab/MotionGPT/assets/975963/8cc352e8-1874-4f3b-ab9e-c08889d21564)

**Comment by SeuGuoTong** [comment]
How was the final resolution achieved? I'm facing the same issue now. Thank you so much for your help!

**Comment by SeuGuoTong** [comment]
May I ask if you have made any changes to 'VQVAEV3_CB1024_CMT-H1024N_RES3'? Where is the location?
