### ISSUE TITLE
About the 'get_motion_code.py'

### ISSUE THREAD

**Issue by huifu99** [OpenMotionLab/MotionGPT#16]
Do you forget to load the pretrained weights for VQ-VAE when generating the tokens?
![image](https://github.com/OpenMotionLab/MotionGPT/assets/115330188/c081d849-bef3-4fab-a259-583272a0b1b0)

**Comment by billl-jiang** [comment]
Thank you for discovering the bug. This error was caused during our code cleanup process and has now been fixed.
