### ISSUE TITLE
About the Motion-Language Pre-training Stage?

### ISSUE THREAD

**Issue by huifu99** [OpenMotionLab/MotionGPT#18]
Are there some mistakes when choicing a condition?
![image](https://github.com/OpenMotionLab/MotionGPT/assets/115330188/1da8b3e5-e4fc-4572-b854-52bcd29d976f)

**Comment by billl-jiang** [comment]
Hi, @huifu99 
Here is the switch for the supervised condition. Currently, we have implemented it in a hardcoded manner, but we will incorporate config item in next version to allow for more flexible configuration.

**Comment by huifu99** [comment]
But you mentioned that both supervised and unsupervised manner are used at the Motion-Language Pre-training Stage. Should I change the code here during training?
![image](https://github.com/OpenMotionLab/MotionGPT/assets/115330188/96d5e7cc-34da-42d4-8350-e34592c039e0)

**Comment by ChenFengYe** [comment]
Hi, you should not change this training now. This pre-training is prepared for some specific version of MotionGPT, which will come later. You can wait for our online demo for testing and use SFT for training now. We will inform you once this part is ready. Thanks bro!
