### ISSUE TITLE
run demo.py meet parameter missing(issue #17 additional details)

### ISSUE THREAD

**Issue by shouyezhe** [OpenMotionLab/MotionGPT#19]
Thanks for excellent work!
I have reviewed issue #17 and noticed that others have faced similar problems. 
Issue Description:
In the context you've mentioned, running demo.py requires certain parameters like 'render' and 'frame_rate,' but I couldn't locate them in the parameter table. I'm unsure about how to resolve this issue and would appreciate your assistance.Thanks.
![267278978-1da49512-e0d4-4d71-a513-d253c49d2026](https://github.com/OpenMotionLab/MotionGPT/assets/50647795/561c4974-945c-4831-9b16-1da165886f19)

**Comment by billl-jiang** [comment]
Hi, @shouyezhe 

Our first version of the code contains some remnants of old code that do not affect the functionality. We have fixed this issue in the subsequent version yesterday. You can try pulling the latest version and give it a try.
