### ISSUE TITLE
Are you familiar with the other MotionGPT?

### ISSUE THREAD

**Issue by felipe-parodi** [OpenMotionLab/MotionGPT#2]
[Another MotionGPT paper was preprinted](https://arxiv.org/pdf/2306.10900.pdf) earlier this week and it'd be helpful to explicitly contrast the two!

**Comment by ChenFengYe** [comment]
Hi, thanks for your attention as well! After reviewing the paper in question, it is evident that both papers concentrate on motion tasks in conjunction with language models. Indeed, the concept of motion-language pre-training is a compelling idea. We feel sorry about the duplication of the project name.  We have also prepared a pre-print version, which will be available shortly.

While it appears that the other paper focuses solely on text-driven motion generation tasks (our current opinion), our MotionGPT encompasses a broader range of motion tasks, such as motion capture and motion QA. As the title of our paper suggests, we treat motion as "word" tokens, providing a foundational framework for numerous other tasks.
