### ISSUE TITLE
T5ForConditionalGeneration.from_pretrained HeaderTooLarge

### ISSUE THREAD

**Issue by kruzel** [OpenMotionLab/MotionGPT#29]
when running app.py

![image](https://github.com/OpenMotionLab/MotionGPT/assets/975963/fa3ec34c-74e5-4084-aaa2-8f3319d8baca)

**Comment by kruzel** [comment]
my bad, didn't have glf installed

**Comment by stefanoalletto** [comment]
hi, I'm getting the same error, do you mind sharing what was missing? I don't see glf among the dependencies and didn't get any errors when installing them?
