### ISSUE TITLE
Will the code be released? 

### ISSUE THREAD

**Issue by morganavr** [OpenMotionLab/MotionGPT#3]
I can see only PDF but not code on Github.

**Comment by ChenFengYe** [comment]
Hi, we will try to release everything of MotionGPT, just like our previous work [Motion-Latent-Diffusion](https://github.com/ChenFengYe/motion-latent-diffusion) (CVPR 2023). You can also check that work if it helps. We are working hard on code-cleaning, setup, and demo. Thanks!

**Comment by ChenFengYe** [comment]
@morganavr Hi, thank you for your kind attention.
We plan to release the first version (v1.0) of MotionGPT on September 9th.
Furthermore, more models and add-ons will also be introduced in the future.
We hope this work could help your research or development. Thanks!
