### ISSUE TITLE
Unauthorized for url: https://huggingface.co/deps/whisper-large-v2

### ISSUE THREAD

**Issue by kruzel** [OpenMotionLab/MotionGPT#30]
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/deps/whisper-large-v2/resolve/main/preprocessor_config.json

**Comment by kruzel** [comment]
configs/assets.yaml
model.whisper_path: deps/whisper-large-v2 to openai/whisper-large-v2

**Comment by GoBigxs** [comment]
Hi. Probably I met the same issue.
OSError: deps/whisper-large-v2 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
How did you fix it?
