### ISSUE TITLE
The blender rendered image seems upside down

### ISSUE THREAD

**Issue by ruizhaogit** [OpenMotionLab/MotionGPT#32]
Dear authors,

Thank you for the great work!
The rendered image from the blender seems upside down:
![frame_0019](https://github.com/OpenMotionLab/MotionGPT/assets/18663623/96046674-50f0-4eef-a855-eeca8cb02942)

Do you know how to solve this?

Thank you!

Best,
Rui

**Comment by ruizhaogit** [comment]
36_out.mp4

**Comment by billl-jiang** [comment]
Hi, @ruizhaogit 

This issue arises from improper axis processing during the rendering of rigged cylinders, while the SMPL meshes remain unaffected. We have released an updated version of the rendering code on GitHub, which you can pull and try out.
