### ISSUE TITLE
AttributeError: 'Joints' object has no attribute 'joinst

### ISSUE THREAD

**Issue by hdjsjyl** [OpenMotionLab/MotionGPT#36]
Hi Author,
    I am a newer to human motion.
    Hopefully, you can give me some suggestions.
    While rendering by custom prompts, I got this issue. 

    AttributeError: 'Joints' object has no attribute 'joinst

        if jointstype == "mmm":
            self.kinematic_tree = mmm_kinematic_tree
            self.joints = mmm_joints
            self.joinst.append("")                                                     // the error happens here
        elif jointstype == "humanml3d":
            self.kinematic_tree = humanml3d_kinematic_tree
            self.joints = humanml3d_joints

    How should I solve this issue?
    Thanks

**Comment by billl-jiang** [comment]
Thank you for your feedback. This is an unexpected typo that does not affect the functionality of the code. We have released an updated version of the rendering code on GitHub.
