### ISSUE TITLE
The rendered image is upside down for custom prompt

### ISSUE THREAD

**Issue by hdjsjyl** [OpenMotionLab/MotionGPT#37]
Hi Author,
    while using custom prompt results to render video,
    The rendered image is upside down for custom prompt

<img width="492" alt="image" src="https://github.com/OpenMotionLab/MotionGPT/assets/7590139/fbfbc91e-d281-48cb-9fd2-123b5840e9a0">

Any suggestion is appreciated, thanks

**Comment by billl-jiang** [comment]
Hi, @hdjsjyl 

This issue arises from improper axis processing during the rendering of rigged cylinders, while the SMPL meshes remain unaffected. We have released an updated version of the rendering code on GitHub, which you can pull and try out.
