### ISSUE TITLE
When will the code be released? As well as ability to fine tune?

### ISSUE THREAD

**Issue by smandava98** [OpenMotionLab/MotionGPT#5]
Hi. Thanks for the great work and for making this public. What is the expected timeline for the code as well as instructions on how to fine tune?

**Comment by ChenFengYe** [comment]
Thanks! We'll release all of MotionGPT, like our prior work, [Motion-Latent-Diffusion](https://github.com/ChenFengYe/motion-latent-diffusion) (CVPR 2023). Expect the demo and training in a month, and full release with fine-tuning instructions in two months.

**Comment by tshrjn** [comment]
Any updates?

**Comment by khannabeela** [comment]
Hello. Thanks for the amazing work. Eagerly waiting for the code.

**Comment by ChenFengYe** [comment]
@tshrjn @khannabeela @smandava98  Hi, thank you all for your kind attention.
We plan to release the first version (v1.0) of MotionGPT on September 9th.
Furthermore, more models and add-ons will also be introduced in the future.
We hope this work could help your research or development. Thanks!
