### ISSUE TITLE
Error loading Pre-trained flan-t5-base

### ISSUE THREAD

**Issue by gkuberreddy** [OpenMotionLab/MotionGPT#68]
Hi,
     Thanks for your great work. I am currently trying to run demo.py using the command shown in your ReadMe file. However, I get the error while loading the pre-trained model. The error is at the pre-trained model loading from a local repo where flan-t5-base is already there and I give the path to that local directory. PFA the erorr I am getting and look forward to your solution for this
     
     
<img width="609" alt="Screenshot 2024-01-04 at 12 06 41 PM" src="https://github.com/OpenMotionLab/MotionGPT/assets/41450325/4d5118e1-3d19-40f5-a09a-31758c505658">
<img width="749" alt="Screenshot 2024-01-04 at 12 06 34 PM" src="https://github.com/OpenMotionLab/MotionGPT/assets/41450325/b040a765-4b27-4be3-986c-9cc17ab645cf">

Thanks in advance.

**Comment by gkuberreddy** [comment]
@billl-jiang , Thank you very much for the quick response. That worked.

**Comment by Pcookie** [comment]
> @billl-jiang , Thank you very much for the quick response. That worked.

Hello, I still don't understand the above meaning. Do I need to modify some code in the Python project, or what should I do? Execute that command in the project directory, but what path should I fill in for "files to download"?
